name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: WordPress/wporg-repo-tools/.github/actions/setup@trunk
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        uses: WordPress/wporg-repo-tools/.github/actions/lint@trunk
